#ifndef _TREAS_STATUS_H_
#define _TREAS_STATUS_H_

#include <Treas/Types.h>

#define TREAS_STATUS_SUCCESS ((LONG)0)
#define TREAS_STATUS_UNSUCCESSFUL ((LONG)-2)
#define TREAS_STATUS_INVALID_PARAMETER ((LONG)-3)
#define TREAS_STATUS_ACCESS_DENIED ((LONG)-4)
#define TREAS_STATUS_INVALID_HANDLE ((LONG)-5)
#define TREAS_STATUS_NO_MEMORY ((LONG)-6)

#endif
