#ifndef _TREAS_USER_ABI_H_
#define _TREAS_USER_ABI_H_

#define TREAS_USER_ABI_VERSION 1

#define TREAS_SYSTEM_CALL_WRITE_BUFFER 1
#define TREAS_SYSTEM_CALL_EXIT 2
#define TREAS_SYSTEM_CALL_YIELD 3
#define TREAS_SYSTEM_CALL_CREATE_THREAD 4
#define TREAS_SYSTEM_CALL_EXIT_THREAD 5
#define TREAS_SYSTEM_CALL_QUERY_SYSTEM_INFORMATION 6
#define TREAS_SYSTEM_CALL_READ_BUFFER 7
#define TREAS_SYSTEM_CALL_WRITE_ERROR_BUFFER 8
#define TREAS_MAX_SYSTEM_CALL_WRITE_SIZE 65536ULL
#define TREAS_MAX_SYSTEM_CALL_READ_SIZE 65536ULL

#endif
