#ifndef _TREAS_USER_OBJECT_H_
#define _TREAS_USER_OBJECT_H_

#include <Treas/Types.h>

#define TREAS_OBJECT_OPERATION_CREATE_EVENT 1u
#define TREAS_OBJECT_OPERATION_SET_EVENT 2u
#define TREAS_OBJECT_OPERATION_RESET_EVENT 3u
#define TREAS_OBJECT_OPERATION_WAIT 4u
#define TREAS_OBJECT_OPERATION_CLOSE 5u

#define TREAS_EVENT_MODIFY_STATE 0x0001u
#define TREAS_SYNCHRONIZE 0x0002u

typedef struct _TREAS_OBJECT_REQUEST {
    ULONG Operation;
    ULONG Handle;
    ULONG DesiredAccess;
    ULONG Flags;
} TREAS_OBJECT_REQUEST, *PTREAS_OBJECT_REQUEST;

#define TREAS_EVENT_MANUAL_RESET 0x0001u
#define TREAS_EVENT_INITIAL_STATE 0x0002u

#endif
