#ifndef _TREAS_USER_VIRTUAL_MEMORY_H_
#define _TREAS_USER_VIRTUAL_MEMORY_H_

#include <Treas/Types.h>

#define TREAS_VM_OPERATION_ALLOCATE 1u
#define TREAS_VM_OPERATION_RELEASE 2u
#define TREAS_VM_OPERATION_PROTECT 3u

#define TREAS_VM_PROTECT_READ 0x01u
#define TREAS_VM_PROTECT_WRITE 0x02u
#define TREAS_VM_PROTECT_EXECUTE 0x04u

typedef struct _TREAS_VIRTUAL_MEMORY_REQUEST {
    ULONGLONG BaseAddress;
    ULONGLONG RegionSize;
    ULONG Operation;
    ULONG Protection;
} TREAS_VIRTUAL_MEMORY_REQUEST, *PTREAS_VIRTUAL_MEMORY_REQUEST;

#endif
